stages:
  - basic
  - deploy

documentation:
  stage: basic
  image: python:3.8-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx furo
    - python -m pip install sphinx_rtd_theme
    - python -m pip install -r requirements.txt
    - python setup.py install
  script:
    - cd docs && make html
  artifacts:
    paths:
      - docs/build/html/

pages:
  stage: deploy
  image: python:3.8-slim
  dependencies:
    - documentation
  script:
    - mkdir public/
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
