include:
  - project: computing/gitlab-ci-templates
    file:
      - conda.yml
      - python.yml

stages:
  - build
  - basic
  - pipeline
  - docs
  - deploy

.parallel_wvf: &parallel_wvf
  parallel:
    matrix:
      - WVF: ["IMRPhenomXPHM", "IMRPhenomTPHM"]

tarball:
  extends:
    - .python:build
  stage: build
  needs: []

conda:
  extends:
    - .conda:base
  stage: build
  needs: []
  script:
    - conda create --name py310 python=3.10
    - conda activate py310
    - conda install -c conda-forge pip2conda
    - python -m pip2conda --output environment.txt
    - conda install --file environment.txt
    - python -m pip install .

executables:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  before_script:
    - python -m pip install simple-pe*.tar.*
  script:
    - simple_pe_analysis --help
    - simple_pe_corner --help
    - simple_pe_filter --help
    - simple_pe_pipe --help

.metric:
  stage: pipeline
  image: python:3.8
  needs:
    - tarball
    - executables
  before_script:
    - python -m pip install simple-pe*.tar.*
  script:
    - cd examples/GW150914
    - bash GW150914.sh
    - mv ./outdir/output/corner.png ../../${WVF}_GW150914_corner.png
    - cd ../..
  artifacts:
    paths:
        - ${WVF}_GW150914_corner.png

.injections:
  extends: .metric
  script:
    - cd examples/zero-noise
    - bash zero-noise.sh
    - mv ./outdir/output/corner.png ../../${WVF}_injection_corner.png
    - cd ../..
  artifacts:
    paths:
        - ${WVF}_injection_corner.png

GW150914:
  <<: *parallel_wvf
  extends: .metric
  variables:
    METRIC_DIRECTIONS: chirp_mass symmetric_mass_ratio chi_align
    PREC_DIRECTIONS: symmetric_mass_ratio chi_align chi_p

injections:zero-noise:
  <<: *parallel_wvf
  extends: .injections

documentation:
  stage: docs
  image: python:3.7
  needs:
    - tarball
    - GW150914
    - injections:zero-noise
  before_script:
    - python -m pip install .[docs]
    - python -m pip install simple-pe*.tar.*
  script:
    - mv IMRPhenomXPHM_GW150914_corner.png docs/source/images
    - mv IMRPhenomTPHM_GW150914_corner.png docs/source/images
    - mv IMRPhenomXPHM_injection_corner.png docs/source/images
    - mv IMRPhenomTPHM_injection_corner.png docs/source/images
    - cd docs && make html
  artifacts:
    paths:
      - docs/build/html/

pages:
  stage: deploy
  image: python:3.8-slim
  dependencies:
    - conda
    - tarball
    - documentation
  script:
    - mkdir public/
    - mv docs/build/html/* ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
