include:
  - project: computing/gitlab-ci-templates
    file:
      - conda.yml
      - python.yml

stages:
  - build
  - basic
  - deploy

tarball:
  extends:
    - .python:build
  stage: build
  needs: []

conda:
  extends:
    - .conda:base
  stage: build
  needs: []
  script:
    - conda create --name py310 python=3.10
    - conda activate py310
    - conda install -c conda-forge pip2conda
    - python -m pip2conda --output environment.txt
    - conda install --file environment.txt
    - python -m pip install .

executables:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  before_script:
    - python -m pip install simple-pe*.tar.*
  script:
    - simple_pe_analysis --help
    - simple_pe_corner --help
    - simple_pe_filter --help
    - simple_pe_pipe --help

documentation:
  stage: basic
  image: python:3.7
  needs:
    - tarball
  before_script:
    - python -m pip install .[docs]
    - python -m pip install simple-pe*.tar.*
  script:
    - cd docs && make html
  artifacts:
    paths:
      - docs/build/html/

pages:
  stage: deploy
  image: python:3.8-slim
  dependencies:
    - conda
    - tarball
    - documentation
  script:
    - mkdir public/
    - mv docs/build/html/* ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
