include:
  - project: computing/gitlab-ci-templates
    file:
      - conda.yml
      - python.yml

stages:
  - build
  - basic
  - pipeline
  - deploy

.parallel_wvf: &parallel_wvf
  parallel:
    matrix:
      - WVF: ["IMRPhenomXPHM", "IMRPhenomTPHM"]

tarball:
  extends:
    - .python:build
  stage: build
  needs: []

conda:
  extends:
    - .conda:base
  stage: build
  needs: []
  script:
    - conda create --name py310 python=3.10
    - conda activate py310
    - conda install -c conda-forge pip2conda
    - python -m pip2conda --output environment.txt
    - conda install --file environment.txt
    - python -m pip install .

executables:
  stage: basic
  image: python:3.8
  needs:
    - tarball
  before_script:
    - python -m pip install simple-pe*.tar.*
  script:
    - simple_pe_analysis --help
    - simple_pe_corner --help
    - simple_pe_filter --help
    - simple_pe_pipe --help

documentation:
  stage: basic
  image: python:3.7
  needs:
    - tarball
  before_script:
    - python -m pip install .[docs]
    - python -m pip install simple-pe*.tar.*
  script:
    - cd docs && make html
  artifacts:
    paths:
      - docs/build/html/

.metric:
  stage: pipeline
  image: python:3.8
  needs:
    - tarball
    - executables
  before_script:
    - python -m pip install simple-pe*.tar.*
  script:
    - cd examples/GW150914
    - sed -i "s/approximant=IMRPhenomXPHM/approximant=${WVF}/g" config.ini
    - simple_pe_pipe config.ini
    - bash ./outdir/submit/bash_simple_pe.sh
    - mv ./outdir/output/peak_parameters.json ../../peak_parameters.json
    - mv ./outdir/output/peak_snrs.json ../../peak_snrs.json
    - mv ./outdir/output/corner.png ../../corner.png
    - cd ../..
  artifacts:
    paths:
        - peak_parameters.json
        - peak_snrs.json
        - corner.png

.injections:
  extends: .metric
  script:
    - cd examples/zero-noise
    - sed -i "s/approximant=IMRPhenomXPHM/approximant=${WVF}/g" config.ini
    - simple_pe_pipe config.ini
    - bash ./outdir/submit/bash_simple_pe.sh
    - bash zero-noise.sh
    - mv ./outdir/output/peak_parameters.json ../../peak_parameters.json
    - mv ./outdir/output/peak_snrs.json ../../peak_snrs.json
    - mv ./outdir/output/corner.png ../../corner.png
    - cd ../..
  artifacts:
    paths:
        - peak_parameters.json
        - peak_snrs.json
        - corner.png

GW150914:
  <<: *parallel_wvf
  extends: .metric

injections:zero-noise:
  <<: *parallel_wvf
  extends: .injections

pages:
  stage: deploy
  image: python:3.8-slim
  dependencies:
    - conda
    - tarball
    - documentation
  script:
    - mkdir public/
    - mv docs/build/html/* ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
